"""empty message

Revision ID: 19de8128115c
Revises: 742f7f343c3a
Create Date: 2025-10-28 13:59:03.341300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19de8128115c'
down_revision = '742f7f343c3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('period_type', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_recipe_tag_slug', ['slug'])

    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_recipe_slug', ['slug'])

    with op.batch_alter_table('recipe_tag', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_period_type_slug', ['slug'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_tag', schema=None) as batch_op:
        batch_op.drop_constraint('slug', type_='unique')

    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_constraint('slug', type_='unique')

    with op.batch_alter_table('period_type', schema=None) as batch_op:
        batch_op.drop_constraint('slug', type_='unique')

    # ### end Alembic commands ###
