"""empty message

Revision ID: 4077fa6b8a72
Revises: ff64a851fa3a
Create Date: 2026-02-01 01:54:08.749624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4077fa6b8a72'
down_revision = 'ff64a851fa3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('like', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_like_recipe_user', ['recipe_id', 'user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('like', schema=None) as batch_op:
        batch_op.drop_constraint('uq_like_recipe_user', type_='unique')

    # ### end Alembic commands ###
