"""empty message

Revision ID: 550452ef26b6
Revises: 62e865ded9b0
Create Date: 2026-01-03 14:35:50.705305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '550452ef26b6'
down_revision = '62e865ded9b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_user_profile_picture_id', 'profile_picture', ['profile_picture_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_profile_picture_id', type_='foreignkey')
        batch_op.drop_column('profile_picture_id')

    # ### end Alembic commands ###
