"""empty message

Revision ID: 551a046a681d
Revises: 49bb99d094bc
Create Date: 2025-10-22 12:35:28.411343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '551a046a681d'
down_revision = '49bb99d094bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
