"""empty message

Revision ID: 70256cee2385
Revises: 19de8128115c
Create Date: 2025-11-01 12:03:39.252746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70256cee2385'
down_revision = '19de8128115c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_superuser', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_superuser')

    # ### end Alembic commands ###
