"""empty message

Revision ID: 7b26ab003073
Revises: 944a1ae00454
Create Date: 2025-12-04 02:42:36.222652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b26ab003073'
down_revision = '944a1ae00454'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_publication_application', schema=None) as batch_op:
        batch_op.alter_column('last_reviewed_by_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_publication_application', schema=None) as batch_op:
        batch_op.alter_column('last_reviewed_by_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
