"""empty message

Revision ID: cae6c74fe47d
Revises: 62e865ded9b0
Create Date: 2026-01-09 20:10:29.043144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cae6c74fe47d'
down_revision = '62e865ded9b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile_picture',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_user_profile_picture_id', 'profile_picture', ['profile_picture_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_profile_picture_id', type_='foreignkey')
        batch_op.drop_column('profile_picture_id')

    op.drop_table('profile_picture')
    # ### end Alembic commands ###
