"""empty message

Revision ID: ff64a851fa3a
Revises: cae6c74fe47d
Create Date: 2026-01-14 17:04:09.596151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff64a851fa3a'
down_revision = 'cae6c74fe47d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_publication_application', schema=None) as batch_op:
        batch_op.alter_column('comment',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_publication_application', schema=None) as batch_op:
        batch_op.alter_column('comment',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
