services:
  web:
    build: .
    env_file:
      - test.env
    volumes:
      - log_files:/var/log/
    expose:
      - 5000
    command: python -m gunicorn run:app --workers=3 --bind 0.0.0.0:5000
  nginx:
    build: 
      context: .
      dockerfile: nginx/dockerfile
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - log_files:/var/log/
    ports:
      - "80:80"

volumes:
  log_files: