FROM nginx:latest

# Install dos2unix to ensure that the entrypoint file starts as expected
RUN apt update
RUN apt install -y dos2unix

COPY scripts/nginx/entrypoint.sh /entrypoint.sh
RUN dos2unix /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT [ "/entrypoint.sh" ]